services:
  admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 80
    labels:
      - traefik.http.routers.pgadmin.rule=PathPrefix(`/pgadmin`)
    environment:
      - SCRIPT_NAME=/pgadmin
    networks:
      - traefik-net

  master:
    image: bitnami/postgresql:latest
    container_name: postgres-master
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
      - ./replication-user-grant.sql:/docker-entrypoint-initdb. d/db.sql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master # 복제 모드 [master / slave]
      - POSTGRESQL_REPLICATION_USER=repl_user
    networks:
      - traefik-net

  slave:
    image: bitnami/postgresql:latest
    container_name: postgres-slave
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave # 복제 모드 [master / slave]
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    depends_on:
      - master
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
